profile_manager/profile_manager/urls.py
"""
Definition of urls for profile_manager.
"""

from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from uploads import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^update/form/$', views.update_profile, name='update_profile'),

    url(r'^uploads/form/$', views.create_profile, name='create_form'),
    url(r'^search/form/$', views.search_profile, name='search_form'),
    url(r'^search_verify/form/$', views.search_for_verification, name='search_for_verification_form'),
    url(r'^verify/form/$', views.verify, name='verify'),


    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_manager/uploads/models.py
from __future__ import unicode_literals

from django.db import models


class Document(models.Model):
    firstname = models.CharField(max_length=255, blank=True)
    lastname = models.CharField(max_length=255, blank=True)
    department = models.CharField(max_length=255, blank=True)
    employee_id = models.AutoField(primary_key=True)
    photo = models.ImageField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

profile_manager/uploads/forms.py
from django import forms

from uploads.models import Document
from uploads.faceDetector import draw_face
from io import BytesIO
from PIL import Image
import base64
from django.core.exceptions import ValidationError
class DocumentForm(forms.Form):

    
    firstname = forms.CharField( max_length=255)
    lastname = forms.CharField( max_length=255)
    department = forms.CharField( max_length=255)
    employee_id = forms.IntegerField(required =False, widget=forms.HiddenInput())
    photo = forms.ImageField()

    def clean_photo(self):
        image_validator=1
        image = self.cleaned_data['photo']
        if type(image) is str:
            im = image.open(image)
        else: im= image

        face_no, image_drawn = draw_face(image.file.read())
        
        if face_no ==0:
            image_validator=0
        if face_no >1:
            image_validator=2

        return (image_validator, image, image_drawn)


        
       
       

profile_manager/uploads/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import base64
from uploads.models import Document
from uploads.forms import DocumentForm
from uploads.faceDetector import draw_face
from uploads.faceDetector import photo_verify

from io import BytesIO
from PIL import Image
from django.shortcuts import get_object_or_404


def home(request):
    documents = Document.objects.all()
    return render(request, 'home.html', { 'documents': documents })


def update_profile(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        employee_id = ''
        if form.is_valid():
            image_validator, origin_image, image_drawn = form.cleaned_data['photo']
            #def the uploaded image has 1 face and is valid
            if (image_validator==1):
                print(request.POST)
                employee_id = form.cleaned_data['employee_id']
                record = Document.objects.get(employee_id=employee_id)
                record.photo=origin_image
                record.firstname=form.cleaned_data['firstname']
                record.lastname=form.cleaned_data['lastname']
                record.department=form.cleaned_data['department']

                record.save()

            buffered = BytesIO()


        #face_no, image_drawn = draw_face(image.file.read())

            image_drawn.save(buffered, format="JPEG")
            b64_img = base64.b64encode((buffered.getvalue()))
            one_face= image_validator==1
            #multi_face = image_validator>1
            no_face = image_validator==0

    


            return render(request, 'view_form.html', {
        'form': form, 'image_drawn':b64_img,'one_face':one_face, 'no_face': no_face, 'employee_id': employee_id
    })

    else:
        form = DocumentForm()
    return render(request, 'create_form.html', {
        'form': form
    })


def create_profile(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        employee_id=""

        if form.is_valid():
            image_validator, origin_image, image_drawn = form.cleaned_data['photo']
            #def the uploaded image has 1 face and is valid
            if (image_validator==1):
                record = Document()
                record.photo=origin_image
                record.firstname=form.cleaned_data['firstname']
                record.lastname=form.cleaned_data['lastname']
                record.department=form.cleaned_data['department']

                record.save()
                employee_id=record.employee_id

            buffered = BytesIO()


        #face_no, image_drawn = draw_face(image.file.read())

            image_drawn.save(buffered, format="JPEG")
            b64_img = base64.b64encode((buffered.getvalue()))
            one_face= image_validator==1
            #multi_face = image_validator>1
            no_face = image_validator==0

    


            return render(request, 'view_form.html', {
        'form': form, 'image_drawn':b64_img,'one_face':one_face, 'no_face': no_face, 'employee_id': employee_id
    })

    else:
        form = DocumentForm()
    return render(request, 'create_form.html', {
        'form': form
    })
def search_profile(request):
    

    employee_id = request.GET['employee_id']
    if (employee_id!=""):
        print("employee id is", employee_id)
        try:
            doc = Document.objects.get(employee_id=employee_id)
        except:
            return render(request, 'search_form.html', {'error_employee_id':employee_id})


        firstname = doc.firstname
        lastname = doc.lastname
        department = doc.department
        id = doc.employee_id
        image = doc.photo
        _, image_drawn = draw_face(image.file.read())

        buffered = BytesIO()



        image_drawn.save(buffered, format="JPEG")
        b64_img = base64.b64encode((buffered.getvalue()))




        return render(request, 'search_result_form.html', {
    'image_drawn':b64_img, 'employee_id': doc.employee_id, 'firstname': firstname, 'lastname': lastname, 'department': department
})

    else:
        return render(request, 'search_form.html')

def search_for_verification(request):
    

    employee_id = request.GET['employee_id']
    if (employee_id!=""):
        print("employee id is", employee_id)
        try:
            doc = Document.objects.get(employee_id=employee_id)
        except:
            return render(request, 'search_for_verification_form.html', {'error_employee_id':employee_id})


        firstname = doc.firstname
        lastname = doc.lastname
        department = doc.department
        id = doc.employee_id
        image = doc.photo
        _, image_drawn = draw_face(image.file.read())

        buffered = BytesIO()



        image_drawn.save(buffered, format="JPEG")
        b64_img = base64.b64encode((buffered.getvalue()))




        return render(request, 'verification_form.html', {
    'image1':b64_img, 'employee_id': doc.employee_id, 'firstname': firstname, 'lastname': lastname, 'department': department
})

    else:
        return render(request, 'search_for_verification_form.html')

def verify(request):
        employee_id = request.POST['employee_id']
        new_photo = request.FILES['photo']
        print("employee id is", employee_id)
        doc = Document.objects.get(employee_id=employee_id)


        firstname = doc.firstname
        lastname = doc.lastname
        department = doc.department
        image = doc.photo
        match, image_on_file, new_photo_drawn = photo_verify(image.file.read(), new_photo.file.read())
        print("Match:", match)
        buffered1 = BytesIO()
        buffered2 = BytesIO()

        image_on_file.save(buffered1, format="JPEG")
        new_photo_drawn.save(buffered2, format="JPEG")

        b64_img1 = base64.b64encode((buffered1.getvalue()))
        b64_img2 = base64.b64encode((buffered2.getvalue()))




        return render(request, 'verification_form.html', {
    'image1':b64_img1,'image2':b64_img2, 'employee_id': employee_id, 'firstname': firstname, 'lastname': lastname, 'department': department, 'match':match
})


        

profile_manager/uploads/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Simple File Upload</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

profile_manager/uploads/templates/create_form.html
{% extends 'base.html' %}

{% block content %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Save</button>
  </form>

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}

profile_manager/uploads/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h3>Menu</h3>
  <ul>

    <li>
      <a href="{% url 'create_form' %}">Create new profile</a>
    </li>
      <li>
      <a href="{% url 'search_form' %}?employee_id=">Search/update profile</a>
    </li>
            <li>
      <a href="{% url 'search_for_verification_form' %}?employee_id=">Verify through photo</a>
    </li>
  </ul>

  <h3>Created records</h3>
 
<table>
  <tr>
    <th>ID </th>
    <th>  First Name</th> 
    <th>  Last Name</th>
    <th>  Profile Picture</th>

  </tr>




    {% for obj in documents %}
      <tr>
             
<td>{{ obj.employee_id }} </td>
          
        <td>{{ obj.firstname }}   </td>  
         <td>{{ obj.lastname }}</td> 
         <td><img src="{{ obj.photo.url }}" width="150" height="100"   ></td> 



      </tr>
    {% endfor %}
</table>

{% endblock %}

profile_manager/uploads/templates/model_form_upload.html
{% extends 'base.html' %}

{% block content %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Save</button>
  </form>

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}

profile_manager/uploads/templates/search_for_verification_form.html
{% extends 'base.html' %}

{% block content %}

  <form method="get" action="">
    {% csrf_token %}
      Employee ID: <input type="text" name="employee_id" value="{{error_employee_id}}">	
      {% if error_employee_id %}
     <p> Employee ID {{error_employee_id}} does not exist! try another id </p>
      {%endif%}

    <button type="submit">Go to verification</button>
  </form>

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}

profile_manager/uploads/templates/search_form.html
{% extends 'base.html' %}

{% block content %}

  <form method="get" action="">
    {% csrf_token %}
      Employee ID: <input type="text" name="employee_id" value="{{error_employee_id}}">	
      {% if error_employee_id %}
     <p> Employee ID {{error_employee_id}} does not exist! try another id </p>
      {%endif%}

    <button type="submit">Retrieve profile</button>
  </form>

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}

profile_manager/uploads/templates/search_result_form.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data" action="/update/form/">
    {% csrf_token %}




 <p><label for="id_employee_id">Employee ID:</label> <input type="text" readonly name="employee_id" value="{{employee_id}}" maxlength="10" id="id_employee_id" /></p>

 <p><label for="id_firstname">First Name:</label> <input type="text" name="firstname" value="{{firstname}}" maxlength="255" id="id_firstname" /></p>

<p><label for="id_lastname">Last Name:</label> <input type="text" name="lastname" value="{{lastname}}" maxlength="255" id="id_lastname" /></p>

<p><label for="id_department">Department:</label> <input type="text" name="department" value="{{department}}" maxlength="255" id="id_department" /></p>


    <button type="submit">Update profile</button>
<p><label for="id_photo">Change photo:</label> <input type="file" name="photo"  id="id_photo" /></p>

  </form>


<img src="data:image/png;base64,{{image_drawn}}" width="500" height="450" />

  <p><a href="{% url 'home' %}">Return to home</a></p>

{% endblock %}

profile_manager/uploads/templates/update_form.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <p><label for="firstname">Employee ID:</label>
            {{employee_id}}
</p>


    {{ form.as_p }}


    <button type="submit">Save</button>
  </form>
{% if one_face %}
   <p>The picture is valid, profile is updated successfully!</p>
{% elif no_face %}
   <p>The picture is invalid, no face is recognized, please select a valid picture</p>
{% else %}
   <p>The picture is invalid, more than one face are detected, please select a valid picture</p>
{% endif %}
<img src="data:image/png;base64,{{image_drawn}}" width="500" height="450" />

  <p><a href="{% url 'home' %}">Return to home</a></p>

{% endblock %}

profile_manager/uploads/templates/verification_form.html
{% extends 'base.html' %}

{% block content %}




 <p><label for="id_employee_id">Employee ID:</label> <input type="text" readonly name="employee_id" value="{{employee_id}}" maxlength="10" id="id_employee_id" /></p>

 <p><label for="id_firstname">First Name:</label> <input type="text" readonly name="firstname" value="{{firstname}}" maxlength="255" id="id_firstname" /></p>

<p><label for="id_lastname">Last Name:</label> <input type="text" readonly name="lastname" value="{{lastname}}" maxlength="255" id="id_lastname" /></p>

<p><label for="id_department">Department:</label> <input type="text" readonly name="department" value="{{department}}" maxlength="255" id="id_department" /></p>
<img src="data:image/png;base64,{{image1}}" width="500" height="450" />


 {% if image2 %}
 {% if match %}
   <p>Matched!</p>
{% else %}
   <p>Cannot verify with the provided picture</p>
{% endif %}
<img src="data:image/png;base64,{{image2}}" width="500" height="450" />
{% endif %}

 <form method="post" enctype="multipart/form-data" action="/verify/form/">
         {% csrf_token %}


<p><label for="id_photo">Select a photo to verify: </label> <input type="file" name="photo"  id="id_photo" /></p>
     <input type="hidden"  name="employee_id" value="{{employee_id}}" maxlength="10" id="id_employee_id" />

         <button type="submit">Submit </button>

  </form>



  <p><a href="{% url 'home' %}">Return to home</a></p>

{% endblock %}

profile_manager/uploads/templates/view_form.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <p><label for="firstname">First Name:</label>
            {{form.uploaded_atd}}
</p>


    {{ form.as_p }}


    <button type="submit">Save</button>
  </form>
<img src="data:image/png;base64,{{image_drawn}}" width="300" height="300" />

  <p><a href="{% url 'home' %}">Return to home</a></p>

{% endblock %}